/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-09-05 06:00:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.project;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class projectInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1660185375234L));
    _jspx_dependants.put("jar:file:/D:/program/fundingTemp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/fundingProj/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../font/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../font/jquery-ui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("\r\n");
      out.write("		var titleArea = document.getElementById(\"title\")\r\n");
      out.write("		var contentArea = document.getElementById(\"content\")\r\n");
      out.write("		var wnameArea = document.getElementById(\"wname\")\r\n");
      out.write("		var targetamountArea = document.getElementById(\"targetamount\")\r\n");
      out.write("		var priceArea = document.getElementById(\"price\")\r\n");
      out.write("\r\n");
      out.write("		var pp = \".*[.](jpeg|jpg|bmp|png|gif|pdf)\";\r\n");
      out.write("		$(\"input[type=submit]\").click(function() {\r\n");
      out.write("\r\n");
      out.write("			if (titleArea.value == \"\") {\r\n");
      out.write("				alert(\"제품명을 입력하세요.\")\r\n");
      out.write("				return false\r\n");
      out.write("			}\r\n");
      out.write("			if (wnameArea.value == \"\") {\r\n");
      out.write("\r\n");
      out.write("				alert(\"제품 소개의 사용할 사진을 확인해주세요.\")\r\n");
      out.write("				return false\r\n");
      out.write("			}\r\n");
      out.write("			if (contentArea.value == \"\") {\r\n");
      out.write("\r\n");
      out.write("				alert(\"첨부할 사진을 확인해주세요.\")\r\n");
      out.write("				return false\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			if (targetamountArea.value == \"\") {\r\n");
      out.write("				alert(\"목표 금액을 입력해주세요.\")\r\n");
      out.write("				return false\r\n");
      out.write("			}\r\n");
      out.write("			if (priceArea.value == \"\") {\r\n");
      out.write("				alert(\"제품 금액을 입력해주세요.\")\r\n");
      out.write("				return false\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			return true\r\n");
      out.write("		})\r\n");
      out.write("\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"ProjectInsertReg\" method=\"post\"\r\n");
      out.write("	enctype=\"multipart/form-data\">\r\n");
      out.write("	<div class=\"projectInsert\">\r\n");
      out.write("		<p class=\"title\">제품등록하기</p>\r\n");
      out.write("\r\n");
      out.write("		<fieldset>\r\n");
      out.write("			<legend>회사명</legend>\r\n");
      out.write("			<input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ifDto.company }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"company\" readonly />\r\n");
      out.write("		</fieldset>\r\n");
      out.write("\r\n");
      out.write("		<fieldset>\r\n");
      out.write("			<legend>제품명</legend>\r\n");
      out.write("			<input type=\"text\" name=\"title\" id=\"title\" />\r\n");
      out.write("		</fieldset>\r\n");
      out.write("\r\n");
      out.write("		<fieldset>\r\n");
      out.write("			<legend>닉네임</legend>\r\n");
      out.write("			<input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ifDto.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"nickname\" readonly />\r\n");
      out.write("		</fieldset>\r\n");
      out.write("\r\n");
      out.write("		<fieldset>\r\n");
      out.write("			<legend>제품소개</legend>\r\n");
      out.write("			<input type=\"file\" name=\"wname\" id=\"wname\" /> <span>사진만가능합니다.ex)\r\n");
      out.write("				jpeg, jpg, bmp, png, gif, pdf</span>\r\n");
      out.write("		</fieldset>\r\n");
      out.write("\r\n");
      out.write("		<fieldset>\r\n");
      out.write("			<legend>제품자세히</legend>\r\n");
      out.write("			<input type=\"file\" name=\"content\" id=\"content\" /> <span>사진만가능합니다.ex)\r\n");
      out.write("				jpeg, jpg, bmp, png, gif, pdf</span>\r\n");
      out.write("		</fieldset>\r\n");
      out.write("\r\n");
      out.write("		<fieldset>\r\n");
      out.write("			<legend>목표금액</legend>\r\n");
      out.write("			<input type=\"text\" name=\"targetamount\" id=\"targetamount\" />\r\n");
      out.write("		</fieldset>\r\n");
      out.write("\r\n");
      out.write("		<fieldset>\r\n");
      out.write("			<legend>금액</legend>\r\n");
      out.write("			<input type=\"text\" name=\"price\" id=\"price\" />\r\n");
      out.write("		</fieldset>\r\n");
      out.write("\r\n");
      out.write("		<fieldset>\r\n");
      out.write("			<legend>카테고리</legend>\r\n");
      out.write("			<select name=\"cat\">\r\n");
      out.write("				<option value=\"clothes\">의류</option>\r\n");
      out.write("				<option value=\"bag\">가방</option>\r\n");
      out.write("				<option value=\"medicine\">약품</option>\r\n");
      out.write("			</select>\r\n");
      out.write("		</fieldset>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"buttonArea\">\r\n");
      out.write("			<input type=\"submit\" value=\"등록\"> \r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
